[package]
name = "karty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom= {version= "7.1.1", optional = true}
array2d = {version = "0.2.1", optional = true}


[features]
parse= ["dep:nom"]
register = ["dep:array2d"]
